/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/theme`; params?: Router.UnknownInputParams; } | { pathname: `/start`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/main`; params?: Router.UnknownInputParams; } | { pathname: `/main/party/create`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/congratulationsSetup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/kycSetup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/membershipSetup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/professionSetup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/profileSetup`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/start`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/main`; params?: Router.UnknownOutputParams; } | { pathname: `/main/party/create`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/congratulationsSetup`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/kycSetup`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/membershipSetup`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/professionSetup`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/profileSetup`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/theme${`?${string}` | `#${string}` | ''}` | `/start${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/main${`?${string}` | `#${string}` | ''}` | `/main/party/create${`?${string}` | `#${string}` | ''}` | `/onboarding/congratulationsSetup${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/kycSetup${`?${string}` | `#${string}` | ''}` | `/onboarding/membershipSetup${`?${string}` | `#${string}` | ''}` | `/onboarding/professionSetup${`?${string}` | `#${string}` | ''}` | `/onboarding/profileSetup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/theme`; params?: Router.UnknownInputParams; } | { pathname: `/start`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/main`; params?: Router.UnknownInputParams; } | { pathname: `/main/party/create`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/congratulationsSetup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/kycSetup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/membershipSetup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/professionSetup`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/profileSetup`; params?: Router.UnknownInputParams; };
    }
  }
}
